version: 2
jobs:
  build:
    docker: 
      - image: circleci/node:12.6-browsers
    steps:
      - checkout
      - restore_cache:
          key: v1-dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          key: v1-dependency-cache-{{ checksum "package.json" }}
          paths:
            - ~/.cache
            - ./node_modules
      - run: yarn test
      - run:
          name: e2e cypress tests
          command: yarn cytest
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
